// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLMmmGhvX4qV260cCVasK004Dcakih9rc',
    appId: '1:516485529277:web:26f785ce631b0c8fc5c1d4',
    messagingSenderId: '516485529277',
    projectId: 'ordinal-case-468211-v8',
    authDomain: 'ordinal-case-468211-v8.firebaseapp.com',
    storageBucket: 'ordinal-case-468211-v8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIAHKTa7ouqlF_plQ11DXpSGpLtF-BJl0',
    appId: '1:516485529277:android:b47a0425b98ce121c5c1d4',
    messagingSenderId: '516485529277',
    projectId: 'ordinal-case-468211-v8',
    storageBucket: 'ordinal-case-468211-v8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8eA8jXgn8G9014SUbUNI0jZW_rybMKw',
    appId: '1:516485529277:ios:0c1e9e6a38063ff9c5c1d4',
    messagingSenderId: '516485529277',
    projectId: 'ordinal-case-468211-v8',
    storageBucket: 'ordinal-case-468211-v8.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );
}
